### ISSUE TITLE
nat-type-identifier implementation in Ionic Vue

### ISSUE THREAD

**Issue by johnchen99** [Hutchison-Technologies/nat-type-identifier#2]
May I know if there is replacement for dgram / socket open for Ionic Vue application development? Secondly, may I know if it's possible for other udp4 socket creation library to replace the socket in  `var socket = dgram.createSocket` , for example, [capacitor-udp](https://github.com/unitree-czk/capacitor-udp#readme) ? Thank you for reading my issue as I'm new to both nat and js.

**Comment by jwh-hutchison** [comment]
Hi John, I'm afraid we don't work with Vue, I'm sure that it would be possible to implement this with an alternate UDP library though as long as the packet checking logic is the same as before. You are welcome to fork the library and open a PR if you wish to add support for implementing this in Vue's framework.
